"""Write zone_offset/compare/study/cases.json: C, B1, B2 plus the D rungs.

The baseline cases are copied from the parent study rather than retyped, so their job names and file
patterns stay in sync with the source of truth. The D rungs are generated from params.csv, which is
the only place an offset is defined.

A case is marked 'available' only once its global job reports completion -- cases that are still
'pending' are skipped everywhere downstream (compare/GENERIC_WORKFLOW.md), so this can be re-run at
any point during a batch.

usage: python make_cases.py
"""
import csv
import json
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
ZONE = os.path.dirname(HERE)
ROOT = os.path.dirname(ZONE)
PARENT = os.path.join(ROOT, 'compare', 'study', 'cases.json')
OUT = os.path.join(ZONE, 'compare', 'study', 'cases.json')
PARAMS = os.path.join(ZONE, 'params.csv')
BASELINE = ('C', 'B1', 'B2')
SUFFIXES = ('', 'main', 'top', 'foundation')


def parent_registry():
    """The parent study's cases, falling back to the committed copy if it is being written."""
    try:
        with open(PARENT, encoding='utf8') as fh:
            return json.load(fh)
    except (ValueError, OSError) as e:
        print('note: %s unreadable (%s); using the committed copy' % (PARENT, e))
        txt = subprocess.run(['git', 'show', 'HEAD:compare/study/cases.json'], cwd=ROOT,
                             capture_output=True, text=True, check=True).stdout
        return json.loads(txt)


# coupling variants of a rung: (case, base rung, interface coupling). Built by make_kinematic.py and
# kept out of params.csv, so make_specimen.py can never build one as an ordinary rung.
VARIANTS = [('D3K', 'D3', 'kinematic')]
CASES_T = {}


def c25_case():
    """The corrected reference: C-GLOBAL-1 with EMB-TIMBER influence radius 25 instead of 50."""
    w = 'zone_offset/work/C_GLOBAL_R25'
    j = 'C_GLOBAL_R25'
    return {
        'label': 'C25 (full model, EMB-TIMBER r=25, reference)',
        'short': 'C25',
        'role': 'reference',
        'status': 'available' if os.path.exists(os.path.join(ROOT, w, j + '.odb')) else 'pending',
        'step': 'Step-WIND',
        'jobs': {'global': j, 'substructures': []},
        'files': {
            'odb': ['%s/%s.odb' % (w, j)],
            'inputs': ['%s/%s.%s' % (w, j, e) for e in ('inp', 'dat', 'msg', 'sta', 'log')],
            'completion_check': ['%s/%s.log' % (w, j)],
            'sim': [],
            'cae': [],
        },
    }


def d_case(case, t, role):
    jobs = ['M52%s%s' % (case, s) for s in SUFFIXES]
    g = '%s-GLOBAL' % case
    w = 'zone_offset/work/%s' % case
    inputs = ['%s/%s.inp' % (w, g), '%s/%s.dat' % (w, g), '%s/%s.msg' % (w, g),
              '%s/%s.sta' % (w, g), '%s/%s.log' % (w, g)]
    for j in jobs:
        inputs += ['%s/%s.inp' % (w, j), '%s/%s.dat' % (w, j), '%s/%s.sta' % (w, j)]
    sim = []
    for j in jobs:
        sim += ['%s/%s_Z1.%s' % (w, j, e) for e in ('sim', 'stt', 'mdl', 'prt')]
    return {
        'label': '%s (offset %.0f mm)' % (case, t),
        'short': case,
        'role': role,
        'status': 'pending',
        'step': 'Step-2-WIND',
        'offset_mm': t,
        'jobs': {'global': g, 'substructures': jobs},
        'files': {
            'odb': ['%s/%s.odb' % (w, g), '%s/%s_[0-9]*.odb' % (w, g)],
            'inputs': inputs,
            'completion_check': ['%s/%s.log' % (w, g)],
            'sim': sim,
            'cae': [],
        },
    }


def main():
    par = parent_registry()
    reg = {
        'study': 'portalframe_M52_joint_zone_offset',
        'root': '../../..',
        'units': par.get('units'),
        'abaqus': par.get('abaqus'),
        'reference': 'C25',
        'note': 'Joint-zone size sweep D0 (t=0, B2 partition) .. D6 (t=300, B1 partition), all '
                'wind-only and generated by zone_offset/src from params.csv. Reference C25 = '
                'C_GLOBAL_R25, the full model with EMB-TIMBER influence radius 25 like every '
                'substructure case. C (radius 50), B1 and B2 are kept for traceability only.',
        'order': [],
        'cases': {},
    }
    reg['cases']['C25'] = c25_case()
    reg['order'].append('C25')
    for c in BASELINE:
        if c in par['cases']:
            reg['cases'][c] = dict(par['cases'][c])
            reg['cases'][c]['offset_mm'] = {'B2': 0.0, 'B1': 300.0}.get(c)
            reg['cases'][c]['role'] = 'test'
            reg['cases'][c]['label'] = {
                'C': 'C (full model, EMB-TIMBER r=50, superseded)',
                'B1': 'B1 (published, wind only)',
                'B2': 'B2 (published, wind + user + snow)'}.get(c, reg['cases'][c]['label'])
            reg['order'].append(c)

    with open(PARAMS, newline='', encoding='utf8') as fh:
        rows = [r for r in csv.DictReader(fh) if r['case'].strip()]
    for r in rows:
        case, t, role = r['case'].strip(), float(r['offset_mm']), r['role'].strip()
        if role == 'verification':
            print('%-4s offset %3.0f  skipped: %s' % (case, t, r['note'][:70]))
            continue
        e = d_case(case, t, 'test')
        log = os.path.join(ROOT, 'zone_offset', 'work', case, '%s-GLOBAL.log' % case)
        if os.path.exists(log):
            txt = open(log, errors='replace').read()
            if 'COMPLETED' in txt and 'exited with errors' not in txt:
                e['status'] = 'available'
        reg['cases'][case] = e
        reg['order'].append(case)
        CASES_T[case] = t
        print('%-4s offset %3.0f  %s' % (case, t, e['status']))

    for case, base, coupling in VARIANTS:
        e = d_case(case, CASES_T[base], 'test')
        e['label'] = '%s (%s, all interfaces %s)' % (case, base, coupling)
        e['variant_of'], e['coupling'] = base, coupling
        log = os.path.join(ROOT, 'zone_offset', 'work', case, '%s-GLOBAL.log' % case)
        if os.path.exists(log) and 'COMPLETED' in open(log, errors='replace').read():
            e['status'] = 'available'
        reg['cases'][case] = e
        reg['order'].append(case)
        print('%-4s variant of %s  %s' % (case, base, e['status']))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf8', newline='\n') as fh:
        json.dump(reg, fh, indent=1)
        fh.write('\n')
    print('-> %s   %d cases (%s)' % (OUT, len(reg['order']), ', '.join(reg['order'])))


if __name__ == '__main__':
    main()
